#! /bin/bash

case $0 in
    .*|/*) base=$(dirname $0);;
    *) base=tracer;;
esac

node $(npm explore jalangi2 -- pwd 2>/dev/null)/src/js/commands/jalangi.js \
    --inlineSource --inlineIID \
    --analysis $base/AlmostWeakMap.js \
    --analysis $base/generic-tracer.js \
    --initParam strategy:console \
    "$@" |tail -1
